Addition of HUGGO and GHS datasets
globalgov/manyhealth pull request #20
Opened 2023-02-10 10:39 UTC by jaeltan

# Description

This minor release includes updates to the `agreements` and `organizations` databases. The new `HUGGO` dataset in the `agreements` database includes metadata that has been verified and expanded. The `organizations` database has been expanded to include additional data on the Global Health System collected by Hoffman and Cole (2018). This data is added in the `GHS` dataset.
 
## Data

* Closed #14 by adding `GHS` (short for Global Health System) dataset by Hoffman and Cole (2018) in the `organisations` database
* Closed #15 by adding `HUGGO` dataset, based on a consolidated version of the `GHHR` and `WHO` datasets in the `agreements` database.
* Closed #16 by adding contributions to the `HUGGO` dataset, including the addition and verification of metadata (Title and date -- Beg, Signature, Force, and End -- variables) and sources/url links of treaty texts.
* Removed `texts` database. Treaty texts are in the process of being incorporated into the `agreements` database in the HUGGO dataset. This release excludes the treaty texts as they are being formatted and stored as .txt files to facilitate future use.

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2023-02-10 13:01 UTC, henriquesposito requested changes
Great job, thank you for all the hard work @jaeltan ! I made small suggestions and notes about package names. Thank you!

2023-02-10 16:51 UTC, jhollway commented on DESCRIPTION
> +Version: 0.1.2
Maybe a minor rather than patch update?

2023-02-10 16:51 UTC, jhollway commented on data-raw/organizations/GHS/prepare-GHS.R
> +names <- c("Number", names[1:5], "State", names[6:7])
What if they change the data at the source? Can we change to using variable names here instead?

2023-02-10 16:51 UTC, jhollway commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- HUGGO_new[-109,]
Can we index these by strings instead of numbers in case the source data changes?

2023-02-10 16:51 UTC, jhollway commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +for(i in 1:109){
Change 109 to whatever the length of the list is?

2023-02-13 12:31 UTC, jhollway approved these changes

2023-02-13 12:31 UTC, jhollway commented on .github/CONTRIBUTING.md
> -Contributions to `{manyhealth}`, whether in the form of issue identification, bug fixes, new code or documentation are encouraged and welcome, both from research assistants and (early) users of the p
You can leave the braces around the package name

2023-02-13 12:31 UTC, jhollway commented on README.Rmd
> +[`{manypkgs}`](https://github.com/globalgov/manypkgs) also makes it easy to
Shouldn't this be `{manyhealth}`?

2023-02-13 12:31 UTC, jhollway commented on README.md
> +[`{manypkgs}`](https://github.com/globalgov/manypkgs) also makes it easy
`{manyhealth}`?

2023-02-13 12:31 UTC, jhollway commented on data-raw/organizations/GHS/GHS.csv
> +id,Actor,Code,URL,Type,Headquarters Location,State,Health as primary intent?,Year of Inception
Do any of these actor codes conflict with manystates?

2023-02-13 14:47 UTC, henriquesposito approved these changes
Great job @jael, thank you for all the hard work! There are just a few name changes as pointed by jhollway, but after that we are all good on my side.

2023-02-14 08:09 UTC, jaeltan commented on README.Rmd
> +[`{manypkgs}`](https://github.com/globalgov/manypkgs) also makes it easy to
This paragraph on contributing is the same in all the other packages and refers to `{manypkgs}` as a package to contribute to data or to set up new packages. I think it makes sense as it is now, but if you prefer I'll change it to `{manyhealth}` @jhollway

2023-02-14 08:34 UTC, jaeltan commented on data-raw/organizations/GHS/GHS.csv
> +id,Actor,Code,URL,Type,Headquarters Location,State,Health as primary intent?,Year of Inception
The only possible conflict with `manystates` is for the variable name for State names. I've stuck to 'State' here as the variable name 'Label' used in `manystates` is not as intuitive when there is another variable with Organization names in the dataset (which I've coded under `Organization`).

2023-02-14 08:36 UTC, jhollway commented on data-raw/organizations/GHS/GHS.csv
> +id,Actor,Code,URL,Type,Headquarters Location,State,Health as primary intent?,Year of Inception
I mean that since the GHS organizations actor codes are (also) three-letter codes, there is a potential for conflicts with the ISO-3166 alpha-3 codes used in `{manystates}`. Are there any overlaps?

2023-02-14 08:58 UTC, jaeltan commented on data-raw/organizations/GHS/GHS.csv
> +id,Actor,Code,URL,Type,Headquarters Location,State,Health as primary intent?,Year of Inception
Ok I just did a check, there are 10 codes that overlap (ASA, AST, COG, CRI, DIR, FIN, MEC, PAN, STP, USA). Since we're not making corrections to the coding of the datasets, I could add a note in the preparation script that there are overlaps that users should be aware of if using the data with state data?

2023-02-14 09:12 UTC, jhollway commented on data-raw/organizations/GHS/GHS.csv
> +id,Actor,Code,URL,Type,Headquarters Location,State,Health as primary intent?,Year of Inception
Yes please, that's a good idea. In the future, we might need to create our own manyID for organisations. It can be 4 or 5 letters long to avoid conflicts.

2023-02-14 09:13 UTC, jaeltan commented on data-raw/organizations/GHS/GHS.csv
> +id,Actor,Code,URL,Type,Headquarters Location,State,Health as primary intent?,Year of Inception
Ok I'll add a note for this on the board

2023-02-14 09:26 UTC, merged